{{- if .Values.addons.headlamp -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://kubernetes-sigs.github.io/headlamp/"
      chart: headlamp
      targetRevision: 0.38.0
      path: .
      helm:
        values: |
          fullnameOverride: headlamp
          ingress:
            enabled: true
            ingressClassName: haproxy
            hosts:
              - host: headlamp.localplane
                paths: 
                - path: "/"
                  type: "Prefix"
          
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{ end }}