{{- if index .Values.addons "online-boutique" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique"
    path: .
    targetRevision: "0.10.4"
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}