apiVersion: v2
name: workspace
description: A Helm chart to deploy the localplane addons application in a Kubernetes cluster and custom resources for local development
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: localplane-addons
  version: 0.2.4
  repository: "oci://ghcr.io/brandonguigo/localplane-addons"
