apiVersion: v2
name: local-stack
description: A Helm chart to deploy the k8s-local-bench application in a Kubernetes cluster and custom resources for local development
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: k8s-local-bench
  version: 0.1.0
  repository: "oci://ghcr.io/brandonguigo/k8s-local-bench"
